name: Blog CI/CD
on:
  push:
    branches: master

jobs:
  blog:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Init Node.js
        run: |
          npm install
          echo "init node successful"
      - name: Install Hexo-cli
        run: |
          npm install -g hexo-cli --save
          echo "install hexo successful"
      - name: Build Blog
        run: |
          hexo clean
          hexo g
          echo "build blog successful"

      # -------------- 配置 SSH 认证 --------------
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HEXO_POST }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      # -------------------------------------------

      - name: Deploy Blog
        run: |
          git config --global user.name "ippclub"
          git config --global user.email "ippclub@outlook.com"
          hexo deploy

      - run: echo "Deploy Successful!"
